<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="9.0.25105.12305-wip" />
    <PackageReference Include="RhinoCommon" Version="9.0.25105.12305-wip" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\hops\Hops.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <StartProgram>C:\Program Files\Rhino 9 WIP\System\Rhino.exe</StartProgram>
    <StartArguments></StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>

</Project>
